In [24]:
%load_ext autoreload
%autoreload 2
!cd ~/dev1/scaling-laws-ecnn

import pandas as pd
import numpy as np
import os

PATH = "~/Data/frischs/datasets/adni/"

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [37]:
subjects = {}
image_path = os.path.expanduser(PATH + "ADNI/")

# show elements in the image path
!ls $image_path | head -n 5

print(os.listdir(image_path))

002_S_0295
002_S_0413
002_S_0559
002_S_0619
002_S_0685
ls: write error: Broken pipe
['031_S_1066', '002_S_0729', '057_S_1269', '128_S_1407', '041_S_1425', '131_S_1389', '130_S_0423', '094_S_1402', '067_S_0056', '128_S_0545', '024_S_1307', '057_S_0957', '114_S_1106', '116_S_0382', '024_S_1400', '116_S_1232', '022_S_0066', '007_S_1206', '006_S_1130', '128_S_0225', '136_S_1227', '073_S_0652', '002_S_0782', '114_S_0458', '027_S_0417', '016_S_1092', '141_S_0810', '126_S_0506', '014_S_0558', '051_S_1296', '130_S_1290', '128_S_0272', '073_S_0386', '094_S_0964', '057_S_0941', '022_S_0007', '041_S_0125', '094_S_0531', '035_S_0997', '128_S_0528', '067_S_0607', '128_S_1409', '082_S_1377', '067_S_0243', '041_S_1260', '094_S_1102', '057_S_1217', '027_S_0461', '136_S_0300', '002_S_0619', '002_S_1261', '094_S_1164', '073_S_0518', '023_S_0126', '022_S_0750', '007_S_0041', '022_S_0130', '128_S_1242', '033_S_1284', '013_S_0575', '082_S_0761', '033_S_1098', '011_S_0241', '136_S_0299', '109_S_1114', '067_S_0290', '941_S_1195', '022_S_1394', '007_S_1222', '002_S_0685', '116_S_0649', '141_S_1152', '114_S_0166', '029_S_1215', '036_S_1001', '029_S_0866', '023_S_1289', '941_S_1363', '033_S_0739', '033_S_0923', '027_S_1385', '007_S_0249', '131_S_0497', '130_S_0449', '099_S_0111', '131_S_0319', '005_S_0546', '130_S_0886', '128_S_0947', '127_S_0925', '062_S_0690', '114_S_1103', '006_S_0521', '011_S_0008', '128_S_0863', '127_S_1140', '136_S_0184', '013_S_0325', '029_S_0871', '023_S_1126', '141_S_0767', '114_S_0374', '130_S_1337', '005_S_1341', '094_S_0692', '057_S_0934', '002_S_1268', '128_S_0216', '036_S_0813', '098_S_0149', '109_S_0967', '003_S_0931', '094_S_1398', '007_S_1304', '022_S_0543', '141_S_0340', '128_S_0229', '033_S_0723', '130_S_0969', '128_S_1181', '128_S_0266', '033_S_1308', '016_S_0538', '128_S_0230', '020_S_0883', '133_S_0638', '006_S_0731', '128_S_0517', '067_S_0024', '018_S_0406', '052_S_1352', '011_S_1282', '128_S_0715', '018_S_0369', '027_S_0256', '005_S_0223', '131_S_0691', '052_S_0952', '013_S_0860', '029_S_0878', '029_S_1384', '027_S_0403', '023_S_0217', '027_S_1254', '014_S_0548', '013_S_1276', '023_S_1262', '003_S_1257', '067_S_0284', '141_S_1244', '011_S_0021', '022_S_0129', '007_S_0128', '136_S_0086', '133_S_0771', '006_S_0484', '022_S_0004', '067_S_0828', '027_S_1213', '141_S_1245', '094_S_1330', '027_S_0179', '022_S_1097', '036_S_0760', '041_S_1002', '031_S_0830', '023_S_0625', '023_S_0084', '027_S_0850', '131_S_0457', '023_S_0083', '098_S_0288', '022_S_0961', '128_S_0258', '130_S_0505', '073_S_0311', '016_S_0359', '141_S_1231', '011_S_0362', '007_S_0070', '067_S_1253', '094_S_0711', '099_S_0470', '007_S_0344', '033_S_1309', '041_S_0549', '027_S_1387', '094_S_1090', '014_S_0356', '127_S_0397', '130_S_0285', '941_S_1311', '131_S_1301', '067_S_0045', '041_S_0598', '011_S_0010', '006_S_0322', '035_S_0033', '062_S_0768', '141_S_0697', '126_S_0708', '067_S_0336', '023_S_0030', '099_S_1034', '018_S_0450', '136_S_0195', '029_S_0824', '133_S_1031', '057_S_1379', '052_S_0989', '131_S_0409', '052_S_1168', '007_S_0293', '082_S_0928', '041_S_1420', '036_S_0577', '099_S_1144', '127_S_1382', '114_S_0173', '128_S_0135', '127_S_1032', '011_S_0861', '023_S_1104', '128_S_1406', '141_S_0717', '037_S_1225', '037_S_0501', '007_S_0316', '114_S_0979', '067_S_0812', '067_S_1185', '011_S_0053', '062_S_1091', '036_S_0672', '035_S_0156', '062_S_1099', '033_S_1086', '127_S_0844', '022_S_1351', '011_S_0856', '031_S_1209', '005_S_0572', '116_S_0752', '033_S_0513', '003_S_1021', '023_S_0376', '099_S_0492', '128_S_1408', '126_S_0891', '011_S_1080', '014_S_0519', '035_S_0555', '006_S_0675', '133_S_0913', '062_S_1299', '136_S_0196', '114_S_1118', '114_S_0416', '130_S_0289', '014_S_1095', '131_S_0441', '013_S_0240', '073_S_1207', '136_S_0194', '128_S_0245', '116_S_0487', '051_S_1331', '082_S_0469', '941_S_1295', '094_S_1417', '099_S_0533', '011_S_0326', '136_S_0695', '003_S_1122', '041_S_1010', '073_S_0445', '005_S_0324', '013_S_1205', '013_S_1120', '007_S_0068', '013_S_0699', '005_S_0221', '006_S_0498', '067_S_0019', '128_S_0608', '011_S_0168', '131_S_0123', '130_S_1200', '013_S_0996', '041_S_1418', '133_S_0433', '013_S_1035', '020_S_0899', '036_S_0976', '036_S_1023', '052_S_1054', '052_S_0951', '033_S_1285', '033_S_0733', '133_S_0727', '035_S_0292', '099_S_0534', '109_S_1157', '041_S_0721', '005_S_0602', '023_S_0061', '018_S_0633', '067_S_0059', '141_S_0696', '032_S_0187', '023_S_0887', '126_S_0784', '003_S_1059', '051_S_1131', '067_S_0038', '127_S_0431', '032_S_1101', '036_S_0576', '041_S_1412', '014_S_0169', '035_S_0204', '109_S_1192', '018_S_0142', '016_S_1149', '062_S_1182', '023_S_0078', '029_S_0914', '133_S_0488', '027_S_1335', '011_S_0005', '126_S_0680', '141_S_1255', '027_S_0835', '073_S_1357', '109_S_1014', '128_S_1148', '130_S_0783', '033_S_0514', '013_S_0592', '033_S_1281', '051_S_1123', '016_S_1117', '126_S_1187', '023_S_1190', '116_S_1249', '029_S_0999', '073_S_0909', '128_S_0310', '141_S_1094', '027_S_1045', '007_S_0698', '128_S_0188', '109_S_1183', '109_S_0876', '022_S_1366', '037_S_0588', '036_S_0656', '131_S_0436', '067_S_0176', '128_S_0805', '006_S_0653', '130_S_1201', '057_S_1373', '128_S_0138', '031_S_0568', '141_S_1052', '016_S_1121', '029_S_1218', '027_S_0408', '128_S_0205', '133_S_0493', '128_S_0740', '094_S_1293', '041_S_1411', '126_S_1221', '141_S_0726', '052_S_0671', '014_S_0563', '094_S_0921', '005_S_0222', '018_S_0682', '027_S_0644', '057_S_0839', '141_S_1024', '013_S_1161', '073_S_0565', '033_S_0888', '041_S_0679', '027_S_0118', '109_S_1013', '036_S_0759', '027_S_0485', '130_S_0102', '127_S_0259', '007_S_0414', '062_S_0730', '032_S_1169', '098_S_0884', '020_S_0213', '023_S_1247', '029_S_0836', '062_S_0578', '941_S_1203', '057_S_1007', '021_S_0332', '098_S_0171', '016_S_0354', '005_S_0814', '094_S_1015', '016_S_1028', '051_S_1338', '023_S_0331', '037_S_0303', '016_S_0991', '023_S_0388', '041_S_1423', '024_S_0985', '002_S_0295', '032_S_0718', '005_S_1224', '002_S_0413', '082_S_0304', '013_S_0502', '127_S_1419', '033_S_1283', '127_S_0394', '033_S_0567', '053_S_0621', '033_S_0724', '041_S_1391', '029_S_1073', '041_S_0262', '023_S_0139', '057_S_1265', '002_S_1280', '006_S_0547', '098_S_0667', '018_S_0155', '094_S_1188', '099_S_0372', '007_S_1248', '057_S_0474', '082_S_0641', '006_S_0681', '002_S_1018', '005_S_0929', '127_S_0260', '057_S_0818', '022_S_0014', '016_S_0590', '024_S_1063', '098_S_0896', '023_S_0613', '109_S_0840', '029_S_0843', '094_S_0434', '136_S_0874', '941_S_1194', '133_S_0525', '027_S_0120', '141_S_1137', '099_S_0551', '057_S_1371', '067_S_0020', '041_S_1435', '127_S_1427', '099_S_0051', '052_S_1250', '094_S_1267', '133_S_1170', '013_S_1275', '033_S_1116', '126_S_0405', '016_S_0769', '023_S_0031', '053_S_0389', '033_S_0734', '094_S_1397', '016_S_1326', '126_S_0865', '116_S_1083', '023_S_0604', '128_S_1430', '067_S_0257', '022_S_0219', '133_S_0629', '099_S_0291', '011_S_0016', '011_S_0023', '141_S_0853', '023_S_0916', '094_S_0489', '052_S_1346', '023_S_0093', '036_S_0945', '136_S_0107', '023_S_0081', '027_S_1082', '099_S_0880', '082_S_0640', '041_S_1368', '136_S_0873', '941_S_1197', '014_S_0520', '003_S_1057', '002_S_0938', '033_S_0906', '126_S_1077', '011_S_0022', '067_S_0077', '127_S_0684', '003_S_0908', '041_S_0407', '033_S_0922', '003_S_1074', '029_S_1318', '141_S_1051', '141_S_0852', '141_S_0982', '011_S_0002', '027_S_0307', '033_S_1016', '002_S_0559', '033_S_0511', '057_S_0464', '128_S_1088', '023_S_0058', '082_S_1119', '014_S_0557', '033_S_0920', '128_S_0227', '023_S_1306', '032_S_0479', '022_S_0096', '128_S_1043', '128_S_0500', '057_S_0643', '023_S_1046', '036_S_1135', '130_S_0956', '099_S_0352', '082_S_1079', '051_S_1072', '029_S_1056', '127_S_0112', '036_S_0748', '073_S_0746', '128_S_0611', '014_S_0328', '027_S_1277', '127_S_0622', '099_S_0040', '033_S_0516', '033_S_0725', '141_S_0790', '041_S_0314', '003_S_0981', '082_S_1256', '131_S_0384', '033_S_0741', '029_S_1184', '020_S_1288', '036_S_1240', '128_S_0770', '024_S_1171', '114_S_0601', '133_S_0792', '099_S_0958', '128_S_0200', '114_S_0228', '127_S_0393', '041_S_0898', '141_S_0851', '941_S_1202', '067_S_0110', '133_S_1055', '094_S_1027', '126_S_0709', '023_S_0855', '099_S_0090', '035_S_0341', '067_S_0098', '126_S_0606', '082_S_0832', '002_S_0955', '016_S_0702', '007_S_1339', '099_S_0060', '023_S_0926', '062_S_0793', '002_S_0954', '033_S_0889', '098_S_0172', '029_S_1038', '052_S_1251', '036_S_0869', '126_S_0605', '002_S_1155', '128_S_0522', '003_S_0907', '094_S_1314', '027_S_0948', '018_S_0043', '136_S_0579', '014_S_0357', '053_S_0507', '057_S_0779', '007_S_0101', '109_S_0950', '114_S_0378', '033_S_1279', '128_S_0167', '114_S_0410', '067_S_0177', '130_S_0460', '023_S_0963', '098_S_0160', '109_S_0777', '022_S_0924', '014_S_0658', '127_S_0754', '082_S_0363', '011_S_0003', '136_S_0186', '133_S_0912', '062_S_0535', '005_S_0553', '141_S_1004', '099_S_0054', '029_S_0845', '130_S_0232', '053_S_1044', '094_S_0526', '024_S_1393', '027_S_0116', '036_S_0673', '062_S_1294', '136_S_0426', '051_S_1040', '098_S_0269', '016_S_1138', '032_S_0677', '073_S_0312', '020_S_0097', '041_S_0446', '141_S_0915', '035_S_0048', '002_S_0816', '067_S_0076', '073_S_0089', '067_S_0029', '002_S_1070', '094_S_1241', '011_S_0183', '022_S_0044', '023_S_0042', '141_S_1378', '027_S_1081', '126_S_1340', '109_S_1343', '005_S_0610', '022_S_0544', '136_S_0429', '005_S_0448', '027_S_0404', '041_S_0282', '016_S_1263', '021_S_0753', '053_S_0919', '116_S_0392', '127_S_1210', '018_S_0055', '033_S_1087', '027_S_0074', '013_S_1186']

In [54]:
subjects = {}
image_path = os.path.expanduser(PATH + "ADNI/")

# show elements in the image path

for subject in os.listdir(image_path):
    if subject not in subjects:
        subjects[subject] = {}
    else:
        raise Exception("Duplicate subject: " + subject)
    for type in os.listdir(image_path + "/" + subject):
        if type != "MPR__GradWarp__B1_Correction__N3":
            raise Exception("Unexpected type: " + type)
        for date in os.listdir(image_path + "/" + subject + "/" + type):
            if date not in subjects[subject]:
                subjects[subject][date] = 1
            else:
                raise Exception("Duplicate date: " + date)
            

image_df = pd.DataFrame(columns=["PTID", "date", "path"])
for subject in subjects:
    for date in subjects[subject]:
        image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)


image_df["EXAMDATE"] = image_df["date"].apply(lambda x: x.split("_")[0])
image_df["ID"] = image_df["PTID"] + "_" + image_df["date"]

/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  image_df = image_df.append({"PTID": subject, "date": date, "path": image_path + "/" + subject + "/MPR__GradWarp__B1_Correction__N3/" + date}, ignore_index=True)
/tmp/ipykernel_871050/800507270.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

In [55]:
image_df.ID.value_counts().head(100)

031_S_1066_2006-12-04_12_03_05.0    1
094_S_0434_2007-11-08_11_59_24.0    1
094_S_0434_2007-05-10_11_50_39.0    1
094_S_0434_2009-05-12_12_18_48.0    1
136_S_0874_2010-01-15_12_15_50.0    1
                                   ..
099_S_0051_2007-07-03_07_52_34.0    1
099_S_0051_2008-12-16_09_44_44.0    1
022_S_0014_2006-05-18_14_19_32.0    1
022_S_0014_2008-11-05_14_10_09.0    1
031_S_1066_2008-06-05_12_09_18.0    1
Name: ID, Length: 100, dtype: int64

In [49]:
path_meta = PATH + "meta_same_site/ADNI"
pd.set_option('display.max_columns', None)

path_meta = PATH + "meta_study_data/meta_data/ADNIMERGE_21Feb2024.csv"
df = pd.read_csv(path_meta)
df["ID"] = df["PTID"] + "_" + df["EXAMDATE"]
df.head()

/tmp/ipykernel_871050/3413398582.py:5: DtypeWarning: Columns (19,20,21,50,51,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path_meta)

,RID,COLPROT,ORIGPROT,PTID,SITE,VISCODE,EXAMDATE,DX_bl,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,APOE4,FDG,PIB,AV45,FBB,ABETA,TAU,PTAU,CDRSB,ADAS11,ADAS13,ADASQ4,MMSE,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,LDELTOTAL,DIGITSCOR,TRABSCOR,FAQ,MOCA,EcogPtMem,EcogPtLang,EcogPtVisspat,EcogPtPlan,EcogPtOrgan,EcogPtDivatt,EcogPtTotal,EcogSPMem,EcogSPLang,EcogSPVisspat,EcogSPPlan,EcogSPOrgan,EcogSPDivatt,EcogSPTotal,FLDSTRENG,FSVERSION,IMAGEUID,Ventricles,Hippocampus,WholeBrain,Entorhinal,Fusiform,MidTemp,ICV,DX,mPACCdigit,mPACCtrailsB,EXAMDATE_bl,CDRSB_bl,ADAS11_bl,ADAS13_bl,ADASQ4_bl,MMSE_bl,RAVLT_immediate_bl,RAVLT_learning_bl,RAVLT_forgetting_bl,RAVLT_perc_forgetting_bl,LDELTOTAL_BL,DIGITSCOR_bl,TRABSCOR_bl,FAQ_bl,mPACCdigit_bl,mPACCtrailsB_bl,FLDSTRENG_bl,FSVERSION_bl,IMAGEUID_bl,Ventricles_bl,Hippocampus_bl,WholeBrain_bl,Entorhinal_bl,Fusiform_bl,MidTemp_bl,ICV_bl,MOCA_bl,EcogPtMem_bl,EcogPtLang_bl,EcogPtVisspat_bl,EcogPtPlan_bl,EcogPtOrgan_bl,EcogPtDivatt_bl,EcogPtTotal_bl,EcogSPMem_bl,EcogSPLang_bl,EcogSPVisspat_bl,EcogSPPlan_bl,EcogSPOrgan_bl,EcogSPDivatt_bl,EcogSPTotal_bl,ABETA_bl,TAU_bl,PTAU_bl,FDG_bl,PIB_bl,AV45_bl,FBB_bl,Years_bl,Month_bl,Month,M,update_stamp,ID
0,2,ADNI1,ADNI1,011_S_0002,11,bl,2005-09-08,CN,74.3,Male,16,Not Hisp/Latino,White,Married,0.0,1.33615,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.67,18.67,5.0,28.0,44.0,4.0,6.0,54.5455,10.0,34.0,112.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,35475.0,118233.0,8336.0,1229740.0,4177.0,16559.0,27936.0,1984660.0,CN,-4.31028,-4.11443,2005-09-08,0.0,10.67,18.67,5.0,28.0,44.0,4.0,6.0,54.5455,10.0,34.0,112.0,0.0,-4.31028,-4.11443,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,35475.0,118233.0,8336.0,1229740.0,4177.0,16559.0,27936.0,1984660.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.33615,NaN,NaN,NaN,0.000000,0.00000,0,0,2023-07-07 04:59:40.0,011_S_0002_2005-09-08
1,3,ADNI1,ADNI1,011_S_0003,11,bl,2005-09-12,AD,81.3,Male,18,Not Hisp/Latino,White,Married,1.0,1.10860,NaN,NaN,NaN,741.5,239.7,22.83,4.5,22.00,31.00,8.0,20.0,22.0,1.0,4.0,100.0000,2.0,25.0,148.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,32237.0,84599.0,5319.0,1129830.0,1791.0,15506.0,18422.0,1920690.0,Dementia,-16.24490,-15.82990,2005-09-12,4.5,22.00,31.00,8.0,20.0,22.0,1.0,4.0,100.0000,2.0,25.0,148.0,10.0,-16.24490,-15.82990,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,32237.0,84599.0,5319.0,1129830.0,1791.0,15506.0,18422.0,1920690.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,741.5,239.7,22.83,1.10860,NaN,NaN,NaN,0.000000,0.00000,0,0,2023-07-07 04:59:40.0,011_S_0003_2005-09-12
2,3,ADNI1,ADNI1,011_S_0003,11,m06,2006-03-13,AD,81.3,Male,18,Not Hisp/Latino,White,Married,1.0,1.07796,NaN,NaN,NaN,NaN,NaN,NaN,6.0,19.00,30.00,10.0,24.0,19.0,2.0,6.0,100.0000,NaN,19.0,135.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,31863.0,88580.0,5446.0,1100060.0,2427.0,14400.0,16972.0,1906430.0,Dementia,-14.76900,-13.13950,2005-09-12,4.5,22.00,31.00,8.0,20.0,22.0,1.0,4.0,100.0000,2.0,25.0,148.0,10.0,-16.24490,-15.82990,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,32237.0,84599.0,5319.0,1129830.0,1791.0,15506.0,18422.0,1920690.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,741.5,239.7,22.83,1.10860,NaN,NaN,NaN,0.498289,5.96721,6,6,2023-07-07 04:59:40.0,011_S_0003_2006-03-13
3,3,ADNI1,ADNI1,011_S_0003,11,m12,2006-09-12,AD,81.3,Male,18,Not Hisp/Latino,White,Married,1.0,1.11626,NaN,NaN,NaN,601.4,251.7,24.18,3.5,24.00,35.00,10.0,17.0,31.0,2.0,7.0,100.0000,0.0,21.0,126.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,35576.0,90099.0,5157.0,1095640.0,1596.0,14617.0,17330.0,1903820.0,Dementia,-20.96910,-19.77900,2005-09-12,4.5,22.00,31.00,8.0,20.0,22.0,1.0,4.0,100.0000,2.0,25.0,148.0,10.0,-16.24490,-15.82990,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,32237.0,84599.0,5319.0,1129830.0,1791.0,15506.0,18422.0,1920690.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,741.5,239.7,22.83,1.10860,NaN,NaN,NaN,0.999316,11.96720,12,12,2023-07-07 04:59:40.0,011_S_0003_2006-09-12
4,3,ADNI1,ADNI1,011_S_0003,11,m24,2007-09-12,AD,81.3,Male,18,Not Hisp/Latino,White,Married,1.0,1.06134,NaN,NaN,NaN,NaN,NaN,NaN,8.0,25.67,37.67,10.0,19.0,23.0,1.0,5.0,100.0000,0.0,16.0,275.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,88252.0,97420.0,5139.0,1088560.0,1175.0,14033.0,16398.0,1903420.0,Dementia,-19.71360,-19.89420,2005-09-12,4.5,22.00,31.00,8.0,20.0,22.0,1.0,4.0,100.0000,2.0,25.0,148.0,10.0,-16.24490,-15.82990,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,32237.0,84599.0,5319.0,1129830.0,1791.0,15506.0,18422.0,1920690.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,741.5,239.7,22.83,1.10860,NaN,NaN,NaN,1.998630,23.93440,24,24,2023-07-07 04:59:40.0,011_S_0003_2007-09-12

In [51]:
def join_unique_columns(df1, col1, df2, col2):
    # Check if the values in the columns are unique within each DataFrame
    if df1[col1].is_unique and df2[col2].is_unique:
        # Check if there's any intersection between the values in the two columns
        if not set(df1[col1]).intersection(set(df2[col2])):
            # Perform the join
            result = pd.merge(df1, df2, how='inner', left_on=col1, right_on=col2)
            return result
        else:
            print("Cannot perform join: Intersection of values in the columns is not empty.")
            return None
    else:
        print("Cannot perform join: Values in one or both columns are not unique.")
        print("df1: ", df1[col1].value_counts().head())
        print("df2: ", df2[col2].value_counts().head())
        return None

result = join_unique_columns(image_df, "ID", df, "ID")

Cannot perform join: Values in one or both columns are not unique.
df1:  126_S_0605_2008-06-30    4
023_S_0604_2009-07-10    3
052_S_1346_2007-03-13    3
023_S_1247_2008-08-12    3
128_S_1148_2008-01-17    3
Name: ID, dtype: int64
df2:  128_S_1088_2013-01-23    2
941_S_1195_2011-02-15    2
035_S_4783_2014-03-13    2
114_S_0166_2012-02-13    1
098_S_0171_2011-04-05    1
Name: ID, dtype: int64

In [20]:
value_counts = df.groupby(['COLPROT', 'DX_bl', 'FLDSTRENG']).size().reset_index(name='counts')
value_counts

   COLPROT DX_bl      FLDSTRENG  counts
0    ADNI1    AD  1.5 Tesla MRI     613
1    ADNI1    CN  1.5 Tesla MRI    1031
2    ADNI1    CN    3 Tesla MRI       2
3    ADNI1  LMCI  1.5 Tesla MRI    1883
4    ADNI1  LMCI    3 Tesla MRI       2
5    ADNI2    AD    3 Tesla MRI     423
6    ADNI2    CN  1.5 Tesla MRI     116
7    ADNI2    CN    3 Tesla MRI     894
8    ADNI2  EMCI    3 Tesla MRI    1089
9    ADNI2  LMCI  1.5 Tesla MRI     123
10   ADNI2  LMCI    3 Tesla MRI     745
11   ADNI2   SMC    3 Tesla MRI     273
12  ADNIGO    CN  1.5 Tesla MRI      70
13  ADNIGO    CN    3 Tesla MRI       7
14  ADNIGO  EMCI    3 Tesla MRI     297
15  ADNIGO  LMCI  1.5 Tesla MRI      87
16  ADNIGO  LMCI    3 Tesla MRI       4